services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dtsen_backend
    ports:
      - "7005:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dtsen_frontend
    ports:
      - "5867:80"
    depends_on:
      - backend
    restart: always
